### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by IsraAtGamings** [Falkirks/RankUp#21]
If a player are VIP than he/she is rankup
How to make it not change to groups just prefix/suffix change i use pureperms and pure chat 

Soory Bad english i am froom Indonesia

**Comment by Falkirks** [comment]
Sorry, I can't understand what you mean. You can configure prefixes/suffixes inside pureperms.

**Comment by JackMD** [comment]
Use PureChat and PurePerms both along with RankUp and Slapper plugin as Slapper plugin adds /rca command which is necessary for setting prefix/suffix. Here is a sample code for better understanding on how to set them.
```
---
groups:
  A:
    entrance:
    - s •§a{name} §bRanked Up To §eA
    - setuperm {name} essentials.warps.A
    - warp A {name}
    - setuperm {name} pchat.command.setprefix
    - rca {name} setprefix A
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: []
```
Same would be followed for setsuffix  here is another example.
```---
groups:
  A:
    entrance:
    - s •§a{name} §bRanked Up To §eA
    - setuperm {name} essentials.warps.A
    - warp A {name}
    - setuperm {name} pchat.command.setsuffix
    - rca {name} setsuffixA
    - unsetuperm {name} pchat.command.setsuffix
    exit: []
    perms: []
    members: []
```
But be sure to use Slapper plugin to add /rca command.
