### ISSUE TITLE
Perm

### ISSUE THREAD

**Issue by LewBr** [Falkirks/RankUp#23]
Permissions does't work 

i will add

1:
  entrance: []
  exit: []
  perms:
  `-` pocketmine.command.say
  members: []

but doesnt works! fix this pls

**Comment by JackMD** [comment]
@Falkirks after testing I can confirm this issue still exists.

**Comment by Falkirks** [comment]
The permission doesn't get added?

**Comment by Falkirks** [comment]
From what I can tell the way Group in rankupdoesgroups handles permisssion attachments is entirely wrong.

**Comment by JackMD** [comment]
@Falkirks yes it doesn't.
I used this.
```
---
groups:
  A:
    entrance:
    - say {name} ranked up to A
    exit: []
    perms:
    - pocketmine.command.say
    - -pocketmine.command.me
    members: []
  B:
    entrance:
    - say {name} ranked up to B
    exit: []
    perms:
    - pocketmine.command.say
    members:
    - JackMPlayz
  C:
    entrance:
    - say {name} ranked up to C
    exit: []
    perms: []
    members: []
  D:
    entrance:
    - say {name} ranked up to D
    exit: []
    perms: []
    members: []
...
```
And when i ranked up to A=>B i was unable to use the /say command.

**Comment by Falkirks** [comment]
I have an idea how to fix it, but I can't test it right now, hopefully I have a chance later today.

**Comment by JackMD** [comment]
Maybe add a commit I can test it for you.

**Comment by Falkirks** [comment]
It is probably going to be a bit tricky, I will see

**Comment by JackMD** [comment]
Okay

**Comment by Falkirks** [comment]
Yeah, something weird is going on that I can't quickly see. I will look again later.

**Comment by JackMD** [comment]
Okay take your time.

**Comment by Adam1609** [comment]
open this issue, sometimes the permission doesn't work
@Falkirks can you confirm this?

**Comment by JackMD** [comment]
I thought that Falkirks fixed this. What permissions doesn't work? Maybe you set the config a bit wrong?

**Comment by Adam1609** [comment]
Nope, I didn't set anything wrong, it only work when I reload my server
When ranking up, sometimes Member can't use command like /warp (which I have setting up)

**Comment by JackMD** [comment]
If its not working do it this way. This is how I do used to do and it worked.
```
---
groups:
  A:
    entrance:
    - say {name} ranked up to A
    - setuperm {name} essentials.warps.A
    exit: []
    perms: []
    members: []
  B:
    entrance:
    - say {name} ranked up to B
   - setuperm {name} essentials.warps.B
   - unsetuperm {name} essentials.warps.A
    exit: []
    perms: []
    members: []
...
```
This is an alternative way but you need to have PurePerms for perms and etc.
