### ISSUE TITLE
Tp them in ranks

### ISSUE THREAD

**Issue by erversonkirit** [Falkirks/RankUp#25]
Hello, how do i tp them in ranks like this (e.g.)
J : Erverson
They tp to mine J
Like this
/warp mineJ or /mine J
Please help me ASAP

**Comment by erversonkirit** [comment]
And if their ranks are lower than rank J they cant tp to the mine J

**Comment by erversonkirit** [comment]
How sir i dont know how to add them im using pureperms

**Comment by JackMD** [comment]
@erversonkirit for that you need to add permission to the player. Say for example a player ranks-up to A so in the config under groups you need to add permission i.e. setuperm {name} essentials.warps.A where A is the mine name. Here is a layout.
```
groups:
  A:
    entrance:
    - setuperm {name} essentials.warps.A
    - warp A {name}
    exit: []
    perms: []
    members: []
```
The `warp A {name}` command will tp the player to the mine directly to mine when they rankup to A.
