### ISSUE TITLE
How to Linked Rankup to Pure perms

### ISSUE THREAD

**Issue by IsraAtGamings** [Falkirks/RankUp#26]
Can you tell me how to link pureperms and rankup? I have use 0.3.1 but dosnt work. I do /rankup than it still show previus rank

**Comment by JackMD** [comment]
@IsraAtGamings here is a sample showing how to set a players rank and add perms. Also how to warp/tp a player.
```
---
groups:
  A:
    entrance:
    - s •§a{name} §bRanked Up To §eA
    - setuperm {name} essentials.warps.A
    - warp A {name}
    - setugroup {name} MVP
    exit: []
    perms: []
    members: []
```
