### ISSUE TITLE
Not working. 

### ISSUE THREAD

**Issue by Shelly7w7** [Falkirks/RankUp#52]
I tired putting quotes on ranks but nope not working, a config error occurred.
``
Enabling RankUp v0.4.0
15.07 04:33:46 [Server] Server thread/CRITICAL ErrorException: "yaml_parse(): scanning error encountered during parsing: could not find expected ':' (line 114, column 1), context while scanning a simple key (line 113, column 1)" (EXCEPTION) in "src/pocketmine/utils/Config" at line 155
``

**Comment by Falkirks** [comment]
What editor are you using? You need to get the quote character like `"` and not angled quotes.

**Comment by Shelly7w7** [comment]
I am doing it correctly, now this error occurred
``
Server] Server thread/CRITICAL ErrorException: "yaml_parse(): scanning error encountered during parsing: mapping values are not allowed in this context (line 51, column 5)" (EXCEPTION) in "src/pocketmine/utils/Config" at line 155
``

Groups:
``
---
groups:
  B:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5B§r§c!
    - rca {name} setprefix B
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: []
  C:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5C§r§c!
    - rca {name} setprefix C
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: []
  D:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5D§r§c!
    - rca {name} setprefix D
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: []
  E:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5E§r§c!
    - rca {name} setprefix E
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: []
  F:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5F§r§c!
    - rca {name} setprefix F
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: []
  G:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5G§r§c!
    - rca {name} setprefix G
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: [] 
  H:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5H§r§c!
    - rca {name} setprefix H
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: [] 
  I:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5I§r§c!
    - rca {name} setprefix I
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: [] 
  J:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5J§r§c!
    - rca {name} setprefix I
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: [] 
  K:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5K§r§c!
    - rca {name} setprefix K
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: [] 
  L:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5L§r§c!
    - rca {name} setprefix L
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: [] 
  M:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5M§r§c!
    - rca {name} setprefix M
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: []         
  N:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5N§r§c!
    - rca {name} setprefix N
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: [] 
  O:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5O§r§c!
    - rca {name} setprefix O
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: [] 
  P:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5P§r§c!
    - rca {name} setprefix P
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: []      
  Q:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5Q§r§c!
    - rca {name} setprefix Q
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: []    
  R:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5R§r§c!
    - rca {name} setprefix R
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: []  
  S:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5S§r§c!
    - rca {name} setprefix S
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: []  
  T:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5T§r§c!
    - rca {name} setprefix T
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: [] 
  U:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5U§r§c!
    - rca {name} setprefix U
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: []
  V:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5V§r§c!
    - rca {name} setprefix V
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: []
  W:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5W§r§c!
    - rca {name} setprefix W
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: [] 
  X:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5X§r§c!
    - rca {name} setprefix X
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: [] 
  Y:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5Y§r§c!
    - rca {name} setprefix Y
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: [] 
  Z:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5Z§r§c. You have gained Your Freedom! 
    - rca {name} setprefix Z
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: []                  
...
``

Ranks:
``
ranks: # Define all your ranks here
 "B": 666000
 "C": 666000
 "D": 666000
 "E": 666000
 "F": 666000
 "G": 666000
 "H": 666000
 "I": 666000
 "J": 666000
 "K": 666000
 "L": 666000
 "M": 666000
 "N": 666000
 "O": 666000
 "P": 666000
 "Q": 666000
 "R": 666000
 "S": 666000
 "T": 666000
 "U": 666000
 "V": 666000
 "W": 666000
 "X": 666000
 "Y": 666000
 "Z": 666000
``

**Comment by Falkirks** [comment]
These configs are parsing fine on my server, so I am not sure what is going on here.

**Comment by Shelly7w7** [comment]
Mind sending me your version? With my config and groups yamls

**Comment by Falkirks** [comment]
```yaml
#   _______                       __        __    __
#  /       \                     /  |      /  |  /  |
#  $$$$$$$  |  ______   _______  $$ |   __ $$ |  $$ |  ______
#  $$ |__$$ | /      \ /       \ $$ |  /  |$$ |  $$ | /      \
#  $$    $$<  $$$$$$  |$$$$$$$  |$$ |_/$$/ $$ |  $$ |/$$$$$$  |
#  $$$$$$$  | /    $$ |$$ |  $$ |$$   $$<  $$ |  $$ |$$ |  $$ |
#  $$ |  $$ |/$$$$$$$ |$$ |  $$ |$$$$$$  \ $$ \__$$ |$$ |__$$ |
#  $$ |  $$ |$$    $$ |$$ |  $$ |$$ | $$  |$$    $$/ $$    $$/
#  $$/   $$/  $$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/  $$$$$$$/
#                                                    $$ |
#  The easy prison rankup plugin for PocketMine-MP   $$ |
#                                                    $$/

unleash-the-rankupdoesgroups: true
  # If you set this to false RankUpDoesGroups won't be loaded.
  # This means that you can't set it as your groupmanager.
  # It is highly recommended not to change this
preferred-economy: false
  # Set your preferred economy
  # rankup\\economy\\Economy and rankup\\economy\\PocketMoney are available by default
  # Set to false for autoloading (only officially supported economys will autoload).
preferred-groupmanager: "rankup\\permission\\RankUpDoesGroups"
  # Set your preferred group manager
  # rankup\\permission\\RankUpDoesGroups and rankup\\permission\\PurePerms are available.
  # RankUpDoesGroups is a super barebones alternative for users who don't use PurePerms

ranks: # Define all your ranks here
 "B": 666000
 "C": 666000
 "D": 666000
 "E": 666000
 "F": 666000
 "G": 666000
 "H": 666000
 "I": 666000
 "J": 666000
 "K": 666000
 "L": 666000
 "M": 666000
 "N": 666000
 "O": 666000
 "P": 666000
 "Q": 666000
 "R": 666000
 "S": 666000
 "T": 666000
 "U": 666000
 "V": 666000
 "W": 666000
 "X": 666000
 "Y": 666000
 "Z": 666000

lang:
  ranked-up-paid: "You have been ranked up to %s"
  ranked-up-free: "You have been ranked up to %s"
  group-add-error-paid: "Failed to rankup. Refunded price."
  group-add-error-free: "Failed to rankup. Try again later."
  need-more-money-1: "Looks like you don't have enough money."
  need-more-money-2: "You need %s to rank up."
  missing-economy: "Can't purchase now."
  have-max-rank: "You have the maximum rank."
  command-permission-error: "You don't have permission to rankup."
```

```yaml
---
groups:
  B:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5B§r§c!
    - rca {name} setprefix B
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: []
  C:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5C§r§c!
    - rca {name} setprefix C
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: []
  D:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5D§r§c!
    - rca {name} setprefix D
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: []
  E:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5E§r§c!
    - rca {name} setprefix E
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: []
  F:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5F§r§c!
    - rca {name} setprefix F
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: []
  G:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5G§r§c!
    - rca {name} setprefix G
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: [] 
  H:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5H§r§c!
    - rca {name} setprefix H
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: [] 
  I:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5I§r§c!
    - rca {name} setprefix I
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: [] 
  J:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5J§r§c!
    - rca {name} setprefix I
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: [] 
  K:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5K§r§c!
    - rca {name} setprefix K
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: [] 
  L:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5L§r§c!
    - rca {name} setprefix L
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: [] 
  M:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5M§r§c!
    - rca {name} setprefix M
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: []         
  N:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5N§r§c!
    - rca {name} setprefix N
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: [] 
  O:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5O§r§c!
    - rca {name} setprefix O
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: [] 
  P:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5P§r§c!
    - rca {name} setprefix P
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: []      
  Q:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5Q§r§c!
    - rca {name} setprefix Q
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: []    
  R:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5R§r§c!
    - rca {name} setprefix R
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: []  
  S:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5S§r§c!
    - rca {name} setprefix S
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: []  
  T:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5T§r§c!
    - rca {name} setprefix T
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: [] 
  U:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5U§r§c!
    - rca {name} setprefix U
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: []
  V:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5V§r§c!
    - rca {name} setprefix V
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: []
  W:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5W§r§c!
    - rca {name} setprefix W
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: [] 
  X:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5X§r§c!
    - rca {name} setprefix X
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: [] 
  Y:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5Y§r§c!
    - rca {name} setprefix Y
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: [] 
  Z:
    entrance:
    - setuperm {name} pchat.command.setprefix
    - sm * §l§5{name}§r§c Has Ranked Up To §l§5Z§r§c. You have gained Your Freedom! 
    - rca {name} setprefix Z
    - unsetuperm {name} pchat.command.setprefix
    exit: []
    perms: []
    members: []                  
...
```
